# Generated by Django 4.1.5 on 2024-12-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_options_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='urun_aciklama',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='urun_adet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='urun_adet_gramaj',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='urun_barkod',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='urun_dara',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='urun_etiket',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='urun_fiyat',
            field=models.FloatField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='urun_grup',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='urun_hedef',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='urun_icerik',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='urun_ismi1',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='urun_ismi2',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='urun_izleme',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='urun_kod',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='urun_kodtip',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='urun_max',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='urun_mesaj1',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='urun_mesaj2',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='urun_mesaj3',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='urun_mesaj4',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='urun_mesaj5',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='urun_mesaj6',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='urun_mesaj7',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='urun_mesaj8',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='urun_mesaj9',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='urun_min',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='urun_musteri',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='urun_qrkod',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='urun_resim',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='urun_stt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='urun_tablo',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='urun_tanim',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='urun_tip',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='urun_top_etiket',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
