# Generated by Django 4.1.5 on 2024-12-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_urun_aciklama'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='urun_mensei',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_aciklama',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
