# Generated by Django 4.1.5 on 2024-12-29 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_urun_mensei_alter_product_urun_aciklama'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prices',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Aktif'), ('INACTIVE', 'Pasif')], max_length=100, verbose_name='Status of the category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='Tanımsız', max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, default='Tanımsız', max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Aktif'), ('INACTIVE', 'Pasif')], max_length=100, verbose_name='Status of the product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_aciklama',
            field=models.CharField(blank=True, default='Tanımsız', max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_adet',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_adet_gramaj',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_barkod',
            field=models.CharField(blank=True, default='Tanımsız', max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_dara',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_etiket',
            field=models.CharField(blank=True, default='Tanımsız', max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_fiyat',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_grup',
            field=models.CharField(blank=True, default='Tanımsız', max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_hedef',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_icerik',
            field=models.CharField(blank=True, default='Tanımsız', max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_ismi1',
            field=models.CharField(blank=True, default='Tanımsız', max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_ismi2',
            field=models.CharField(blank=True, default='Tanımsız', max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_izleme',
            field=models.CharField(blank=True, default='Tanımsız', max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_kod',
            field=models.CharField(blank=True, default='Tanımsız', max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_kodtip',
            field=models.CharField(blank=True, default='Tanımsız', max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_max',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_mensei',
            field=models.CharField(blank=True, default='Tanımsız', max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_mesaj1',
            field=models.CharField(blank=True, default='Tanımsız', max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_mesaj2',
            field=models.CharField(blank=True, default='Tanımsız', max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_mesaj3',
            field=models.CharField(blank=True, default='Tanımsız', max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_mesaj4',
            field=models.CharField(blank=True, default='Tanımsız', max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_mesaj5',
            field=models.CharField(blank=True, default='Tanımsız', max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_mesaj6',
            field=models.CharField(blank=True, default='Tanımsız', max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_mesaj7',
            field=models.CharField(blank=True, default='Tanımsız', max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_mesaj8',
            field=models.CharField(blank=True, default='Tanımsız', max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_mesaj9',
            field=models.CharField(blank=True, default='Tanımsız', max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_min',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_musteri',
            field=models.CharField(blank=True, default='Tanımsız', max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_qrkod',
            field=models.CharField(default='Tanımsız', max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_resim',
            field=models.CharField(blank=True, default='Tanımsız', max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_stt',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_tablo',
            field=models.CharField(blank=True, default='Tanımsız', max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_tanim',
            field=models.CharField(blank=True, default='Tanımsız', max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_tip',
            field=models.CharField(blank=True, default='Tanımsız', max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_top_etiket',
            field=models.CharField(blank=True, default='Tanımsız', max_length=256),
        ),
    ]
