# Generated by Django 4.2.17 on 2025-01-13 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_prices_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='urun_mesaj1',
            field=models.TextField(blank=True, default='Tanımsız', max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_mesaj2',
            field=models.TextField(blank=True, default='Tanımsız', max_length=256),
        ),
    ]
