# Generated by Django 4.2.17 on 2025-01-13 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_urun_mesaj1_alter_product_urun_mesaj2'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_aciklama',
            field=models.TextField(blank=True, default='Tanımsız', max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_icerik',
            field=models.TextField(blank=True, default='Tanımsız', max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_mesaj3',
            field=models.TextField(blank=True, default='Tanımsız', max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_mesaj4',
            field=models.TextField(blank=True, default='Tanımsız', max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_mesaj5',
            field=models.TextField(blank=True, default='Tanımsız', max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_mesaj6',
            field=models.TextField(blank=True, default='Tanımsız', max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_mesaj7',
            field=models.TextField(blank=True, default='Tanımsız', max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_mesaj8',
            field=models.TextField(blank=True, default='Tanımsız', max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_mesaj9',
            field=models.TextField(blank=True, default='Tanımsız', max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_tanim',
            field=models.TextField(blank=True, default='Tanımsız', max_length=256),
        ),
    ]
