# Generated by Django 4.1.5 on 2025-01-14 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_fieldsetting_alter_product_urun_aciklama_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FieldSetting',
        ),
    ]
