# Generated by Django 5.0.12 on 2025-03-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_delete_fieldsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='urun_adet_gramaj',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_dara',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_fiyat',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_max',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_min',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
