# Generated by Django 5.1.6 on 2025-03-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_urun_adet_gramaj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='urun_aciklama',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_barkod',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_etiket',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_grup',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_icerik',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_ismi1',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_ismi2',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_izleme',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_kod',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_kodtip',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_mensei',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_mesaj1',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_mesaj2',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_mesaj3',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_mesaj4',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_mesaj5',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_mesaj6',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_mesaj7',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_mesaj8',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_mesaj9',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_musteri',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_qrkod',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_resim',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_tablo',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_tanim',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_tip',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='urun_top_etiket',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
