# Generated by Django 5.2 on 2025-06-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_urun_aciklama_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='urun_tip',
            field=models.CharField(blank=True, choices=[('ADET', 'Adet'), ('AGIRLIK', 'Ağırlık'), ('FIYAT', 'Fiyat'), ('SABITAGIRLIK', 'Sabit Ağırlık')], default='AGIRLIK', max_length=20),
        ),
    ]
