# Generated by Django 5.1.6 on 2025-03-03 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_status_alter_customer_category'),
        ('products', '0013_alter_product_urun_aciklama_and_more'),
        ('sales', '0004_printlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='printlog',
            name='custom_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Özel Metin'),
        ),
        migrations.AddField(
            model_name='printlog',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer', verbose_name='Müşteri'),
        ),
        migrations.AddField(
            model_name='printlog',
            name='customer_address',
            field=models.TextField(blank=True, null=True, verbose_name='Müşteri Adresi'),
        ),
        migrations.AddField(
            model_name='printlog',
            name='customer_name1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Müşteri Adı 1'),
        ),
        migrations.AddField(
            model_name='printlog',
            name='customer_name2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Müşteri Adı 2'),
        ),
        migrations.AddField(
            model_name='printlog',
            name='date_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Üretim Tarihi'),
        ),
        migrations.AddField(
            model_name='printlog',
            name='icerik',
            field=models.TextField(blank=True, null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='printlog',
            name='msg1',
            field=models.TextField(blank=True, null=True, verbose_name='Mesaj 1'),
        ),
        migrations.AddField(
            model_name='printlog',
            name='msg2',
            field=models.TextField(blank=True, null=True, verbose_name='Mesaj 2'),
        ),
        migrations.AddField(
            model_name='printlog',
            name='msg3',
            field=models.TextField(blank=True, null=True, verbose_name='Mesaj 3'),
        ),
        migrations.AddField(
            model_name='printlog',
            name='msg4',
            field=models.TextField(blank=True, null=True, verbose_name='Mesaj 4'),
        ),
        migrations.AddField(
            model_name='printlog',
            name='msg5',
            field=models.TextField(blank=True, null=True, verbose_name='Mesaj 5'),
        ),
        migrations.AddField(
            model_name='printlog',
            name='msg6',
            field=models.TextField(blank=True, null=True, verbose_name='Mesaj 6'),
        ),
        migrations.AddField(
            model_name='printlog',
            name='msg7',
            field=models.TextField(blank=True, null=True, verbose_name='Mesaj 7'),
        ),
        migrations.AddField(
            model_name='printlog',
            name='msg8',
            field=models.TextField(blank=True, null=True, verbose_name='Mesaj 8'),
        ),
        migrations.AddField(
            model_name='printlog',
            name='msg9',
            field=models.TextField(blank=True, null=True, verbose_name='Mesaj 9'),
        ),
        migrations.AddField(
            model_name='printlog',
            name='paket_sayisi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Paket Sayısı'),
        ),
        migrations.AddField(
            model_name='printlog',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Ürün'),
        ),
        migrations.AddField(
            model_name='printlog',
            name='product_barkod',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ürün Barkodu'),
        ),
        migrations.AddField(
            model_name='printlog',
            name='product_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ürün Kodu'),
        ),
        migrations.AddField(
            model_name='printlog',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ürün Adı'),
        ),
        migrations.AddField(
            model_name='printlog',
            name='product_stt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Son Tüketim Tarihi'),
        ),
        migrations.AddField(
            model_name='printlog',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Seri No'),
        ),
        migrations.AddField(
            model_name='printlog',
            name='time_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Saat'),
        ),
        migrations.AddField(
            model_name='printlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='printlog',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dosya Yolu'),
        ),
        migrations.AlterField(
            model_name='printlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Zaman Damgası'),
        ),
        migrations.AlterField(
            model_name='printlog',
            name='weight',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ağırlık'),
        ),
    ]
