# Generated by Django 5.1.6 on 2025-04-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_printlog_custom_text_printlog_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printlog',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
