# Generated by Django 5.2 on 2025-04-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_printlog_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='printlog',
            name='topnet',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
