# Generated by Django 5.2 on 2025-04-12 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_urun_aciklama_and_more'),
        ('sales', '0007_printlog_topnet'),
    ]

    operations = [
        migrations.AddField(
            model_name='printlog',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category', verbose_name='Ürün Kategorisi'),
        ),
    ]
