# Generated by Django 5.2 on 2025-04-12 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_printlog_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printlog',
            name='product_category',
        ),
    ]
