# Generated by Django 5.2 on 2025-04-12 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_urun_aciklama_and_more'),
        ('sales', '0009_remove_printlog_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='printlog',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category', verbose_name='Ürün Kategorisi'),
        ),
    ]
