# Generated by Django 5.2 on 2025-04-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_printlog_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='printlog',
            name='toplam_paket_sayisi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Toplam Paket Sayısı'),
        ),
    ]
