# Generated by Django 4.1.5 on 2025-01-04 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_prices_product_price_and_more'),
        ('customers', '0002_customer_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Aktif'), ('INACTIVE', 'Pasif')], default=1, max_length=100, verbose_name='Status of the customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='category',
            field=models.ForeignKey(db_column='category', on_delete=django.db.models.deletion.CASCADE, related_name='customer_category', to='products.category'),
        ),
    ]
